site_name: Kodoha's page
pages:
    - GitHub: github.md
    - Challenge Automation H21028: challenge-tcb-2018h2.md
    - Build a kintone plugin: build-kintone-plugin.md
    - Reference: reference.md
    - About: about.md
    - How did they do that!?: index.md
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: True